apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "selenium-grid.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/hostname: selenium.mydomain.com.
spec:
  rules:
    - host: selenium.mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "selenium-grid.fullname" . }}
                port:
                  number: 4444