apiVersion: v1
kind: Service
metadata:
  name: {{ include "selenium-grid.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4444
      protocol: TCP
  selector:
    app: {{ include "selenium-grid.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "selenium-grid.fullname" . }}-nodes
spec:
  type: ClusterIP
  ports:
    - port: 5555
      targetPort: 5555
      protocol: TCP
  selector:
    app: {{ include "selenium-grid.name" . }}-nodes
