apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: selenium-grid-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
