
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: selenium-grid-nodes-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: selenium-grid-nodes
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
